### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by lovsfuc1ngsh1t** [lamda-bbo/macro-regulator#2]
![Snipaste_2024-12-06_20-43-01](https://github.com/user-attachments/assets/853545f5-4ab2-4924-b4ce-de35dbd3b160)
Hello, what could I do if I get the following error when I run it and it says I can't find this module? Is there a problem with the sys path? Or is it a cpp compilation problem?

**Comment by DukeTomlist** [comment]
Thank you for your attention to our work! This error may be caused by a sys path problem and we have committed a more stable version of our code. Before the code is merged into the main branch, you can add the following to `main.py`:
```Python
import sys
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BENCHMARK_DIR = os.path.join(ROOT_DIR, "benchmark")
SRC_DIR = os.path.join(ROOT_DIR, "src")
RESULT_DIR = os.path.join(ROOT_DIR, "results")
CONFIG_DIR = os.path.join(ROOT_DIR, "config")
UTILS_DIR = os.path.join(ROOT_DIR, "utils")
DREAMPLACE_PARENT_DIR = os.path.join(ROOT_DIR, "DREAMPlace")
DREAMPLACE_DIR = os.path.join(DREAMPLACE_PARENT_DIR, "dreamplace")
sys.path.extend(
    [ROOT_DIR, BENCHMARK_DIR, SRC_DIR, RESULT_DIR, CONFIG_DIR, UTILS_DIR, DREAMPLACE_PARENT_DIR, DREAMPLACE_DIR]
)
```

If you have any questions, feel free to contact us!

**Comment by DukeTomlist** [comment]
Hi @lovsfuc1ngsh1t 

Thank you for your attention to our work! This error may be caused by a sys path problem and we have committed a more stable version of our code. Before the code is merged into the main branch, you can add the following to `main.py`:
```Python
import sys
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BENCHMARK_DIR = os.path.join(ROOT_DIR, "benchmark")
SRC_DIR = os.path.join(ROOT_DIR, "src")
RESULT_DIR = os.path.join(ROOT_DIR, "results")
CONFIG_DIR = os.path.join(ROOT_DIR, "config")
UTILS_DIR = os.path.join(ROOT_DIR, "utils")
DREAMPLACE_PARENT_DIR = os.path.join(ROOT_DIR, "DREAMPlace")
DREAMPLACE_DIR = os.path.join(DREAMPLACE_PARENT_DIR, "dreamplace")
sys.path.extend(
    [ROOT_DIR, BENCHMARK_DIR, SRC_DIR, RESULT_DIR, CONFIG_DIR, UTILS_DIR, DREAMPLACE_PARENT_DIR, DREAMPLACE_DIR]
)
```

If you have any questions, feel free to contact us!

**Comment by lovsfuc1ngsh1t** [comment]
![1](https://github.com/user-attachments/assets/e1368013-0f5a-463d-b567-b8732d45acc4)

![2](https://github.com/user-attachments/assets/4cc0340a-2e9b-49b0-a4f7-4d9a6c1f0fd3)

![3](https://github.com/user-attachments/assets/be53d42e-b246-4722-aee7-295a139ad0b3)

I added the above code to main.py and still have the following problem, and every function in the DREAMPlace/dreamplace/ops directory has the same problem. Is it possible that these functions require the cpp file to be recompiled, like in [Dreamplace](https://github.com/limbo018/DREAMPlace) ? Or is it that the code needs to be run inside a docker ?
